# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  egl_position:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  egl_position_mimic:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  iiwa_joint_1:
    has_velocity_limits: true
    max_velocity: 1.71042266695
    has_acceleration_limits: true
    max_acceleration: 2
  iiwa_joint_2:
    has_velocity_limits: true
    max_velocity: 1.71042266695
    has_acceleration_limits: true
    max_acceleration: 2
  iiwa_joint_3:
    has_velocity_limits: true
    max_velocity: 1.74532925199
    has_acceleration_limits: true
    max_acceleration: 2
  iiwa_joint_4:
    has_velocity_limits: true
    max_velocity: 2.26892802759
    has_acceleration_limits: true
    max_acceleration: 2
  iiwa_joint_5:
    has_velocity_limits: true
    max_velocity: 2.44346095279
    has_acceleration_limits: true
    max_acceleration: 2
  iiwa_joint_6:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: true
    max_acceleration: 2
  iiwa_joint_7:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: true
    max_acceleration: 2
