controller_list:
  - name: PositionJointInterface_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - $(arg robot_name)_joint_1
      - $(arg robot_name)_joint_2
      - $(arg robot_name)_joint_3
      - $(arg robot_name)_joint_4
      - $(arg robot_name)_joint_5
      - $(arg robot_name)_joint_6
      - $(arg robot_name)_joint_7

  - name: PositionJointInterface_gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - $(arg robot_name)_egl_position_left
      - $(arg robot_name)_egl_position_right
