openapi: 3.0.0
x-navigateMethodsByName: true
info:
  version: 0.1.0
  title: Robot Learning Lab API
servers: 
  - url: https://rll-api.ipr.kit.edu
tags:
- name: jobs
  description: Management of Jobs
- name: system
  description: Retrieve system information
paths:
  /jobs:
    get:
      tags:
      - jobs
      summary: Get status of job or data for job
      description: ''
      operationId: getJobs
      parameters:
      - in: query
        name: op
        description: What operation should be performed, either retrieving status information about job or fetching data of a finished job
        required: true
        schema:
          type: string
          enum:
          - status
          - data_urls
      - in: query
        name: job
        description: Job Id to perform operation on
        required: true
        schema:
          type: string
        example: 5b391e2af7971f5ba880525b
      responses:
        '200':
          description: Response of the call
          content:
            application/json:
              schema:
                type: object
                oneOf:
                  - $ref: '#/components/schemas/JobStatusSuccess'
                  - $ref: '#/components/schemas/JobDataSuccess'
                  - $ref: '#/components/schemas/JobDataError'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
    post:
      tags:
      - jobs
      summary: Submit a job
      description: Central submission of jobs using a single secret. It would also be possible to support OpenID and OAuth to directly authenticate users.
      operationId: submitJob
      parameters:
      - in: query 
        name: op
        description: Operation to perform, either submitting a Git repo URL with a Git tag or a Tar archive with the code
        required: true
        schema:
          type: string
          enum:
          - submit_git
          - submit_tar
      - in: query
        name: username
        description: Author of the submitted code
        required: true
        schema:
          type: string
      - in: query
        name: secret
        description: Password for submission access
        required: true
        schema:
          type: string
          format: password
      - in: query
        name: project
        description: Name of the project the submission is for
        required: true
        schema:
          type: string
          enum:
          - rll_planning_project
      - in: query
        name: git_url
        description: Url to git repository
        schema:
          type: string
      - in: query
        name: git_tag
        description: Tag to checkout in the submitted Git repo
        schema:
          type: string
      - in: query
        name: tar_url
        description: URL to Tar archive with code
        schema:
          type: string
      responses:
        '200':
          description: Response for submission
          content:
            application/json:
              schema:
                type: object
                oneOf:
                - $ref: '#/components/schemas/JobSubmissionSuccess'
                - $ref: '#/components/schemas/JobSubmissionError'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
  /system:
    get:
      tags:
      - system
      summary: Get general information about the lab
      description: ''
      parameters:
      - in: query
        name: op
        description: What operation should be performed
        required: true
        schema:
          type: string
          enum:
          - status
      responses:
        '200':
          description: Response for system state query
          content:
            application/json:
              schema:
                type: string
                enum:
                - online
                - offline
                - down for maintenance
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
components:
  schemas:
    JobStatusSuccess:
      title: Successful job status query
      required:
      - status
      - job_status
      properties:
        status:
          type: string
          description: Status of query
          enum:
          - success
        job_status:
          type: string
          description: Status of job
          enum:
          - submitted
          - processing sim started
          - processing real started
          - downloading code
          - building
          - running sim
          - waiting for real
          - running real
          - finished
        job_result:
          type: string
          description: Result if the job has finished
          enum:
          - success sim
          - success real
          - failure sim
          - failure real
          - internal error
          - unknown
          - fetching project code failed
          - launching project failed
          - building project failed
        job_data:
          type: array
          items:
            type: object
            properties:
              description:
                type: string
                example: duration
              value:
                type: number
        position:
          type: integer
          description: Position in queue if status is submitted or waiting
        cam_url:
          type: string
          description: URL to live stream of running job on robot
    JobDataSuccess:
      title: Successfull query for job data
      required:
      - status
      - build_log_url
      properties:
        status:
          type: string
          description: Status of query
          enum:
          - success
        build_log_url:
          type: string
          description: URL to build log file
        video_url:
          type: string
          description: URL to video file of job
        sim_run_client_log_url:
          type: string
          description: URL to client log file for simulation run
        sim_run_iface_log_url:
          type: string
          description: URL to interface log file for simulation run
        real_run_client_log_url:
          type: string
          description: URL to client log file for the run on the real robot
        real_run_iface_log_url:
          type: string
          description: URL to interface log file for the run on the real robot
    JobDataError:
      title: Failed query for job data
      required:
      - status
      - error
      properties:
        status:
          type: string
          description: Status of query
          enum:
          - error
        error:
          type: string
          description: Error message
          enum:
          - No finished job with this ID
    JobSubmissionSuccess:
      title: Successful submission
      required:
      - status
      - job_id
      properties:
        status:
          type: string
          description: Status of submission
          enum:
          - success
        job_id:
          type: string
          description: Job id of submitted job
          example: 5ab955b109b90e5707d2ccbe
    JobSubmissionError:
      title: Failed submission
      required:
      - status
      - error
      properties:
        status:
          type: string
          description: Status of submission
          enum:
          - error
        error:
          type: string
          description: Error message
          enum:
          - User has a job in the queue
          - Git tag not found
          - Git URL invalid
          - Username invalid
          - Queue at max size
